/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import config.conexion;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class lista_libros extends javax.swing.JFrame {

    /**
     * Creates new form lista_libros
     */
    conexion cn = new conexion();
    Connection con;
    Statement st;
    ResultSet rs;
    DefaultTableModel model;
    public lista_libros() {
        initComponents();
        listar();
        listar2();
        
    }
    void listar(){
        String sql="select id_libro,id_editorial,nombre_libro,num_ejemplares,edicion,autor from libro";
        try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            Object[] libro= new Object[6];
            model = (DefaultTableModel)tabladatos.getModel();
            while(rs.next()){
                libro[0]= rs.getInt("id_libro");
                libro[1]= rs.getString("nombre_libro");
                libro[2]= rs.getInt("edicion");
                libro[3]= rs.getInt("num_ejemplares");
                libro[4]= rs.getString("autor");
                libro[5]= rs.getInt("id_editorial");
                model.addRow(libro);
            }
            tabladatos.setModel(model);
        } catch (Exception e) {
        }
    }
    void agregar(){
        String nombre = txt_titulo.getText();
        String ejemplares= txt_cantidad.getText();
        String edicion = txt_edicion.getText();
        String autor = txt_autor.getText();
        String editorial= txt_idedit.getText();
    }
    void listar2(){
        String sql = "select nombre_editorial from editorial";
       
        try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                cbo_edit.addItem(rs.getString("nombre_editorial"));
            }
        } catch (Exception e) {
        }
    }
    void listar_id(){
        String valor = cbo_edit.getSelectedItem().toString();
        String sql2= "select id_editorial from editorial where nombre_editorial ='"+valor+"'";
        try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            if (rs.next()){
                txt_idedit.setText(rs.getString("id_editorial"));
            }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        txt_titulo = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txt_cantidad = new javax.swing.JTextField();
        txt_edicion = new javax.swing.JTextField();
        txt_autor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbo_edit = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_idedit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("LIBROS ALMACENADOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Libro", "Titulo ", "Edicion", "N. Ejmeplares", "Autor", "Editorial"
            }
        ));
        jScrollPane1.setViewportView(tabladatos);
        if (tabladatos.getColumnModel().getColumnCount() > 0) {
            tabladatos.getColumnModel().getColumn(0).setMinWidth(70);
            tabladatos.getColumnModel().getColumn(0).setPreferredWidth(70);
            tabladatos.getColumnModel().getColumn(0).setMaxWidth(70);
            tabladatos.getColumnModel().getColumn(1).setMinWidth(300);
            tabladatos.getColumnModel().getColumn(1).setPreferredWidth(300);
            tabladatos.getColumnModel().getColumn(1).setMaxWidth(300);
            tabladatos.getColumnModel().getColumn(2).setMinWidth(60);
            tabladatos.getColumnModel().getColumn(2).setPreferredWidth(60);
            tabladatos.getColumnModel().getColumn(2).setMaxWidth(60);
            tabladatos.getColumnModel().getColumn(3).setMinWidth(90);
            tabladatos.getColumnModel().getColumn(3).setPreferredWidth(90);
            tabladatos.getColumnModel().getColumn(3).setMaxWidth(90);
            tabladatos.getColumnModel().getColumn(4).setMinWidth(200);
            tabladatos.getColumnModel().getColumn(4).setPreferredWidth(200);
            tabladatos.getColumnModel().getColumn(4).setMaxWidth(200);
            tabladatos.getColumnModel().getColumn(5).setMinWidth(90);
            tabladatos.getColumnModel().getColumn(5).setPreferredWidth(90);
            tabladatos.getColumnModel().getColumn(5).setMaxWidth(90);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 812, 377));
        jPanel1.add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 335, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 309, -1));

        jButton1.setText("buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));
        jPanel1.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 71, -1));
        jPanel1.add(txt_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 71, -1));
        jPanel1.add(txt_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 193, -1));

        jButton2.setText("Añadir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 66, -1));

        jLabel2.setText("Ejemplares:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 64, -1));

        jLabel3.setText("Edicion:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel4.setText("Autor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 37, -1));

        jButton3.setText("Modificar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        jButton4.setText("Eliminar");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, -1, -1));

        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jPanel1.add(cbo_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 140, 30));

        jLabel6.setText("Editorial:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));
        jPanel1.add(txt_idedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listar_id();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lista_libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lista_libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lista_libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lista_libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lista_libros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_edicion;
    private javax.swing.JTextField txt_idedit;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
